/**
 * Wireframe pattern types and design-system category hints.
 */

export const PATTERN_TYPES = [
  'Button',
  'Input Field',
  'Textarea',
  'Dropdown',
  'Checkbox',
  'Radio Group',
  'Search Bar',
  'Card',
  'Card Grid',
  'Navigation',
  'Tabs',
  'Table',
  'Modal',
  'Sidebar',
  'Avatar',
  'Image Block',
  'Text Block',
  'CTA Group',
  'Form',
  'Form Group',
  'Banner',
  'Carousel',
  'Pagination',
  'Breadcrumb',
  'Header',
  'Link Group',
  'Footer Links',
  'Navigation Links',
  'PlaceholderContent',
  'Hero Section',
  'Content Block',
  'CTA Section',
  'Form Section',
  'Card Grid Section',
  'Footer Section',
  'Image Grid Section',
  'Header Section',
  'Navigation Icon',
  'Heading',
  'Body Text',
  'Paragraph',
  'Description',
  'Label',
  'Carousel Section',
  'Feature List Section',
  'Course Card',
  'Content Card',
  'Course Listing Section',
  'Category Selector',
  'Filter Group',
  'Hero Carousel',
  'Body Container',
  'Bottom Navigation',
];

/** Keywords used to match scanned component names in the design system. */
export const PATTERN_DS_KEYWORDS = {
  Button: ['button', 'btn', 'cta', 'action'],
  'Input Field': ['input', 'field', 'textfield', 'text field'],
  Textarea: ['textarea', 'text area', 'multiline'],
  Dropdown: ['dropdown', 'select', 'menu-select', 'combobox'],
  Checkbox: ['checkbox', 'chk', 'check'],
  'Radio Group': ['radio', 'radio group', 'radiobutton'],
  'Search Bar': ['search', 'searchbar', 'search-bar'],
  Card: ['card', 'tile', 'panel'],
  'Card Grid': ['grid', 'cards-grid', 'card-list'],
  Navigation: ['nav', 'navbar', 'header', 'navigation', 'appbar', 'topbar'],
  Tabs: ['tabs', 'tabbar', 'tab-bar', 'segmented-control'],
  Table: ['table', 'datatable', 'grid-data'],
  Modal: ['modal', 'dialog', 'popup', 'overlay', 'window'],
  Sidebar: ['sidebar', 'side-nav', 'drawer', 'rail', 'navigation-drawer'],
  Avatar: ['avatar', 'profile', 'userpic', 'thumbnail', 'badge-avatar'],
  'Image Block': ['image', 'img', 'photo', 'picture', 'artwork', 'hero-image'],
  'Text Block': ['text-block', 'typography', 'paragraph', 'heading-group', 'copy'],
  'CTA Group': ['cta-group', 'button-group', 'actions', 'action-bar'],
  Form: ['form', 'signup-form', 'login-form', 'contact-form'],
  'Form Group': ['form-group', 'input-group', 'field-container'],
  Banner: ['banner', 'alert-banner', 'promo', 'hero-banner'],
  Carousel: ['carousel', 'slider', 'slideshow'],
  Pagination: ['pagination', 'pager', 'page-control'],
  Breadcrumb: ['breadcrumb', 'breadcrumbs', 'path'],
  Header: ['header', 'appbar', 'topbar', 'navbar'],
  'Link Group': ['links', 'link-group', 'list-links', 'footer-column'],
  'Footer Links': ['footer', 'footer-links', 'footer-nav'],
  'Navigation Links': ['nav-links', 'menu-links', 'menu-items'],
  PlaceholderContent: ['placeholder', 'skeleton', 'shimmer', 'loading'],
  'Hero Section': ['hero', 'banner-hero', 'jumbotron', 'promo-hero'],
  'Content Block': ['content', 'block', 'section-content', 'body', 'text-button'],
  'CTA Section': ['cta', 'call-to-action', 'action-section', 'button-section'],
  'Form Section': ['form', 'input-form', 'section-form'],
  'Card Grid Section': ['grid', 'cards-grid', 'card-list'],
  'Footer Section': ['footer', 'footer-links', 'footer-nav'],
  'Image Grid Section': ['grid', 'gallery', 'images', 'photos', 'placement'],
  'Header Section': ['header', 'navbar', 'nav', 'topbar'],
  'Navigation Icon': ['hamburger', 'menu-icon', 'nav-icon', 'menu-button'],
  Heading: ['heading', 'title', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6'],
  'Body Text': ['body', 'paragraph', 'text', 'copy'],
  Paragraph: ['paragraph', 'text', 'copy', 'para'],
  Description: ['description', 'desc', 'info', 'summary'],
  Label: ['label', 'tag', 'caption', 'badge'],
  'Carousel Section': ['carousel', 'slider', 'slideshow'],
  'Feature List Section': ['features', 'list', 'benefits', 'points'],
  'Course Card': ['course-card', 'course-tile', 'class-card', 'lecture-card'],
  'Content Card': ['content-card', 'blog-card', 'news-card', 'article-card'],
  'Course Listing Section': ['courses-list', 'courses-grid', 'course-listing', 'academy-section'],
  'Category Selector': ['category-selector', 'categories', 'pills-selector', 'tag-selector'],
  'Filter Group': ['filter-group', 'filters', 'refine-panel'],
  'Hero Carousel': ['hero-carousel', 'hero-slider', 'promo-carousel'],
  'Body Container': ['body-container', 'layout-body', 'screen-body', 'page-container'],
  'Bottom Navigation': ['bottom-nav', 'bottom-navigation', 'tabbar-bottom', 'bottom-bar'],
};

/** Default design system category when no component name matches. */
export const PATTERN_DEFAULT_CATEGORY = {
  Button: 'Buttons',
  'Input Field': 'Forms / Inputs',
  Textarea: 'Forms / Textarea',
  Dropdown: 'Forms / Dropdown',
  Checkbox: 'Forms / Checkbox',
  'Radio Group': 'Forms / Radio',
  'Search Bar': 'Forms / Search',
  Card: 'Cards',
  'Card Grid': 'Grids / Layouts',
  Navigation: 'Navigation',
  Tabs: 'Navigation / Tabs',
  Table: 'Tables',
  Modal: 'Overlays / Modals',
  Sidebar: 'Navigation / Sidebar',
  Avatar: 'Avatars / Media',
  'Image Block': 'Media / Image',
  'Text Block': 'Typography',
  'CTA Group': 'Buttons / Groups',
  Form: 'Forms',
  'Form Group': 'Forms / Groups',
  Banner: 'Marketing / Banner',
  Carousel: 'Carousels',
  Pagination: 'Navigation / Pagination',
  Breadcrumb: 'Navigation / Breadcrumb',
  Header: 'Navigation / Header',
  'Link Group': 'Navigation / Links',
  'Footer Links': 'Navigation / Footer',
  'Navigation Links': 'Navigation / Menu',
  PlaceholderContent: 'Placeholders',
  'Hero Section': 'Marketing / Banner',
  'Content Block': 'Typography',
  'CTA Section': 'Buttons / Groups',
  'Form Section': 'Forms',
  'Card Grid Section': 'Grids / Layouts',
  'Footer Section': 'Navigation / Footer',
  'Image Grid Section': 'Media / Image',
  'Header Section': 'Navigation / Header',
  'Navigation Icon': 'Navigation',
  Heading: 'Typography',
  'Body Text': 'Typography',
  Paragraph: 'Typography',
  Description: 'Typography',
  Label: 'Typography',
  'Carousel Section': 'Carousels',
  'Feature List Section': 'Typography',
  'Course Card': 'Cards',
  'Content Card': 'Cards',
  'Course Listing Section': 'Grids / Layouts',
  'Category Selector': 'Navigation',
  'Filter Group': 'Forms / Search',
  'Hero Carousel': 'Carousels',
  'Body Container': 'Grids / Layouts',
  'Bottom Navigation': 'Navigation',
};
